#!/usr/bin/env bash

# === Documentation === #
#
# This script offers a simple trashbin mechanism to my Bash command line, which
# prevents me from accidentally rm-ing my files. It holds the contents of each
# deletion inside `$HOME/.trash/`, with timestamps for each deletion. It also
# clears the trash bin upon command.
# 
# Future expansions will give me the ability to restore file upon command.
# Currently, I have to dig into the timestamped dirs, which is a pain.
#
# === === #

TRASH="$HOME/.trash"

clear-trash() {
  rm -rf "$TRASH"/* && echo "Trash emptied."
}

del() {

  mkdir -p "$TRASH"

  for file in "$@"; do

    # Generate time stamp
    DATETIME=$(date +'%Y%m%dT%H%M%S')

    # Move deleted content to the trash bin
    mkdir -p "$TRASH"/"$DATETIME" \
      && mv "$file" "$TRASH"/"$DATETIME" \
      && echo "Successful deletion."

  done
}
